- name: deploy my app
  hosts: new_vms
  become: true
  vars:
    app_download_server: https://artifactory.pharriso.co.uk
    app_download_path: artifactory/generic-local
  roles:
    - pharriso.jboss.install_jboss_eap
  tasks:
    - name: deploy war file to jboss deployments directory
      get_url:
        url: "{{ app_download_server }}/{{ app_download_path }}/{{ app }}.war"
        dest: "{{ jboss_home }}/standalone/deployments/{{ instance_role }}.war"
        validate_certs: false

    - name: add instance to loadbalancer target group
      elb_target:
        target_group_name: "{{ instance_role }}" 
        target_id: "{{ instance_id }}"
        target_port: 8080
        state: present
        region: "{{ ec2_region }}"
      delegate_to: localhost
      become: false
