---

- name: launch multiple instances
  amazon.aws.ec2:
    region: "{{ ec2_region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image: "{{ ami_id }}"
    wait: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ security_group }}"
    assign_public_ip: yes
    user_data: "{{ lookup('file', 'userdata.txt') | default(omit) }}" 
    instance_tags: "{{ instance_tags }}"
    count_tag: "{{ count_tag }}"
    exact_count: "{{ instance_count }}"
  register: ec2

- name: wait for connection
  ansible.builtin.wait_for:
    host: "{{ item.public_ip }}"
    port: "{{ port | default(22) }}"
    delay: 10
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip }}"

- name: add hosts to play
  add_host:
    name: "{{ item.public_ip }}"
    groups:
    - new_vms
    instance_id: "{{ item.id }}"
  loop: "{{ ec2.instances }}"
  loop_control:
    label: "{{ item.public_ip }}"
